### PR TITLE
fix(FormlyFormController): Fix validateOnModelChange not firing with promise change #523

### LINKED ISSUE #523: bug(formly-form): validateOnModelChange not firing with promise change
@isaac-l noticed that the [Matching Two Fields](http://angular-formly.com/#/example/other/matching-two-fields) example is broken. After some investigation I found that it works with version 7.1.2, but breaks with version 7.2.0 from [this commit](https://github.com/formly-js/angular-formly/commit/460ead54) by @BarryThePenguin.

@BarryThePenguin, I don't have time right now to look at this, but do you suppose you could give it a look? If not, feel free to assign it back to me. Thanks!

### PR DESCRIPTION
**Pull request by Rybbow**
## What

In FormlyFormController in function validateFormControl variable validate was invoked with "undefined" this if the function was called with a promise.

## Why

It's a bug.

## How

Used a closure and apply() to ensure validate() will be called with formController as this.

For issue #523 

Checklist:

* [X] Follows the commit message [conventions](https://github.com/stevemao/conventional-changelog-angular/blob/master/convention.md)
* [X] Is [rebased with master](https://egghead.io/lessons/javascript-how-to-rebase-a-git-pull-request-branch?series=how-to-contribute-to-an-open-source-project-on-github)
* [X] Is [only one (maybe two) commits](https://egghead.io/lessons/javascript-how-to-squash-multiple-git-commits)

Fixes validate being called with undefined this variable scope.

Closes #523

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ed1fcfcda8017dbcf03a0fd0b56040535b511bec
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/formly-js/angular-formly/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by kentcdodds** [comment]
Could someone from @angular-formly-collaborators review and merge this?

**Comment by kentcdodds** [comment]
Sorry, bad @ mention. Someone from @formly-js/angular-formly-collaborators please review and merge this. Thanks.

File: src/directives/formly-form.controller.js [hunk 1]
```diff
@@ -30,7 +30,7 @@ export default function FormlyFormController(
   function validateFormControl(formControl, promise) {
     const validate = formControl.$validate
     if (promise) {
-      promise.then(validate)
+      promise.then(() => validate.apply(formControl))
     } else {
       validate()
```
Comment (BarryThePenguin) [inline src/directives/formly-form.controller.js]: what about this line?

Comment (kentcdodds) [inline src/directives/formly-form.controller.js]: I was thinking that the problem is that the `validate` function isn't being called with the right `this` context. Honestly, I'd prefer the use of `bind` personally, but I don't care either way.

Comment (BarryThePenguin) [inline src/directives/formly-form.controller.js]: Cool. LGTM
